# Generated by Django 4.1 on 2022-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content',
            field=models.CharField(default='ahoj', max_length=99999),
            preserve_default=False,
        ),
    ]
