# Generated by Django 4.1 on 2022-10-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_profile_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
    ]
