# Generated by Django 4.1.2 on 2022-11-03 15:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
