# Generated by Django 4.1.2 on 2022-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_exhibition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='url',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
